name: test
channels:
  - conda-forge
  - defaults
  - omnia-dev
  - omnia
  - openeye
dependencies:
  - python >=3.6
  - pip
  - setuptools
  - fire
  - joblib
  - numpy >=1.14
  - scipy
  - numexpr
  - autograd
  - pymbar
  - openmm >=7.3.1
  - openmoltools # may need to sort out ambermini/ambertools/parmed dependencies (we don't want ambertools)
  - openmmtools # may need to sort out ambermini/ambertools/parmed dependencies
  - numba
  - netcdf4
  - matplotlib
  - seaborn
  - mdtraj
  - pdbfixer
  - lxml
  - networkx >=2.0
  - openeye-toolkits
  - dask
  - dask-jobqueue
  - distributed
  - progressbar2
  - parmed # may need to sort out ambermini/ambertools/parmed dependencies
  - tqdm
  - pytest
  - pytest-cov
  - coverage
  - openff-toolkit
  - sphinx
  - dicttoxml
  - openmmforcefields >=0.9.0
  - dicttoxml
  - tinydb
  - pytest-attrib
  - pytest-xdist
