name: MacMini

on:
  push:

jobs:
  build-and-test:
    defaults:
      run:
        shell: /usr/bin/arch -arch ${{ matrix.runner }} /bin/bash -l {0} 
    runs-on: M1
    env:
      DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
      NSUnbufferedIO: YES 
    strategy:
      fail-fast: false
      matrix:
        runner: [arm64e, x86_64]
    timeout-minutes: 20
    steps:
       - uses: actions/checkout@v2.3.1
       - uses: conda-incubator/setup-miniconda@v2
         with:
           python-version: 3.9
           mamba-version: "*"
           channels: conda-forge,defaults
           channel-priority: true
           activate-environment: test
           environment-file: test_env.yaml
       - shell: bash -l {0}
         run: |
           conda info
           conda list
           conda config --show-sources
           conda config --show
           printenv | sort
           arch
           uname
